version: "2.5"
services:
  # rabbitmq:
  #   image: rabbitmq:3.8.17-management
  #   hostname: 'rabbit'
  #   environment:
  #     - RABBITMQ_DEFAULT_USER=guest
  #     - RABBITMQ_DEFAULT_PASS=guest
  #   ports:
  #     - "15672:15672"

  # redis:
  #   image: redis:latest
  #   ports:
  #     - "6379:6379"

  backend:
    container_name: backend
    build: ./backend
    volumes:
      - ./backend:/app
    ports:
      - 8080:8080
    stdin_open: true
    tty: true